### ISSUE TITLE
Missing OATPP_CODEGEN_END

### ISSUE THREAD

**Issue by heindl-solutions** [oatpp/example-crud#15]
At least in files
`oatpp-example-crud\src\controller\UserController.hpp`
and
`oatpp-example-crud\src\controller\StaticController.hpp`
the macro
`OATPP_CODEGEN_BEGIN`
is used two times.

I think this should be:
OATPP_CODEGEN_BEGIN
...
OATPP_CODEGEN_**END**

**Comment by lganzzzo** [comment]
@heindl-solutions ,

Thanks for pointing this out.
Fixed in https://github.com/oatpp/example-crud/commit/0bea5ad41e230127372a1f5dc0105dacd10e64f7
