### ISSUE TITLE
Duplicate 500 handlers when I think a 404 was intended.

### ISSUE THREAD

**Issue by acidtonic** [oatpp/example-crud#6]
https://github.com/oatpp/example-crud/blob/4c5a3f0dc4f1281a7539aba4f4470df798684a4a/src/controller/UserController.hpp#L37

I see duplicate rows for error 500, when the other examples in the file have 500 and 404, looks like maybe a copy-paste missed it.

Otherwise I am confused why it's there twice.

**Comment by lganzzzo** [comment]
Yep, you are right - copy-paste.
Please feel free to fix it and send a PR.
